version: '2.1'

services:
  visual-search:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - elasticsearch
    environment:
      - "ELASTIC_HOST=elasticsearch"
      - "ELASTIC_PORT=9200"
  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  index-open-images-test-set:
    build:
      context: ./logstash/
      dockerfile: Dockerfile
    links:
      - visual-search
    volumes:
      - ./data:/usr/share/data
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      - "LOG_LEVEL=info"
